### ISSUE TITLE
Performance enhancement

### ISSUE THREAD

**Issue by munrocket** [charto/bigfloat#1]
As you know private methods in javascript have worst performance (check here [question3](https://github.com/ganqqwerty/123-Essential-JavaScript-Interview-Questions#question-3-what-is-the-drawback-of-having-private-methods-in-a-javascript-object)).
And since your library designed to be incredibly fast do you think about static function for arithmetic?
I checked same libraries with multicomponent float expansion in other languages and their performance are [much better](https://github.com/JuliaMath/DoubleFloats.jl) compeared to ordinary arbitrary precision.

**Comment by munrocket** [comment]
Also what about .js distribution? This project maintainable?

**Comment by jjrv** [comment]
[Here's the `.js` file published on npm](https://unpkg.com/bigfloat@0.0.4/dist/index.js).

TypeScript attaches private methods to the prototype, the private keyword here only affects the [`.d.ts` file](https://unpkg.com/bigfloat@0.0.4/dist/index.d.ts).

Speed would improve by supporting more destructive operations that modify a number instead of returning a new object.

The double float approach looks very interesting, I didn't know about it. Triple double should allow working with products of two JavaScript numbers without any rounding errors. It might speed up a robust implementation of Bentley-Ottmann line intersection algorithm, because arbitrary precision computations would be needed less.

**Comment by jjrv** [comment]
It seems a better approach would be to have a static function for multiplying two JavaScript numbers, returning a `BigFloat` wrapping a triple double. Those could then be compared and in some cases added / subtracted while remaining triple doubles. Further operations would switch to arbitrary precision.

**Comment by munrocket** [comment]
Did not notice the .js version in npm package, also you not answered 20 days so it lead me to create my own version :) Also I am trying to find a fulltime job by creating open source libraries.

**Comment by munrocket** [comment]
Yes i think static functions are posible solution.

**Comment by jjrv** [comment]
The new `BigFloat53` class is now based on a multicomponent float expansion.

**Comment by munrocket** [comment]
Nice!

**Comment by munrocket** [comment]
Hello @jjrv can you comment something on fma proposal in JS? https://es.discourse.group/t/math-float-optimisation/829/4
